export const LOADING_PRODUCTS = 'LOADING_PRODUCTS';

export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_PRODUCTS_BY_PRICE = 'GET_PRODUCTS_BY_PRICE';
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
export const GET_PRODUCT_CONDITION = 'GET_PRODUCT_CONDITION';

export const ERROR_PRODUCTS = 'ERROR_PRODUCTS';
